import { afterEach,describe,it,expect,vi } from 'vitest';
import { randomUUID } from 'node:crypto';
import { mkdtemp,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const cloud=vi.hoisted(()=>new Map<string,Buffer>());
vi.mock('qiniu',()=>({default:{conf:{Config:class{},RPC_TIMEOUT:60000},auth:{digest:{Mac:class{}}},rs:{PutPolicy:class{uploadToken(){return 'test-token'}},BucketManager:class{async getBucketInfo(){return {ok:()=>true,data:{region:'as0'}}}privateDownloadUrl(domain:string,key:string){return domain+'/'+key}async delete(_bucket:string,key:string){cloud.delete(key);return {ok:()=>true,resp:{statusCode:200}}}}},form_up:{PutExtra:class{},FormUploader:class{async put(_token:string,key:string,bytes:Buffer){cloud.set(key,bytes);return {ok:()=>true}}}}}}));
vi.mock('@aws-sdk/client-s3',()=>({GetObjectCommand:class{constructor(public input:{Key:string}){}},S3Client:class{destroy(){}async send(command:{input:{Key:string}}){const data=cloud.get(command.input.Key)!;return {ContentLength:data.length,Body:(async function*(){yield data})()}}}}));
vi.mock('node:dns/promises',()=>({lookup:vi.fn(async()=>({address:'8.8.8.8',family:4}))}));
import { storagePath,sealFile,openFile,writeStoredFile,readStoredFile,deleteStoredFile } from '../src/lib/storage';
import { environmentModels,environmentAgent } from '../src/modules/ai/environment';
afterEach(()=>{vi.unstubAllEnvs();vi.unstubAllGlobals();cloud.clear()});
describe('存储与服务器模型安全边界',()=>{
 it('云端密文拒绝篡改、换位和错误密钥',()=>{vi.stubEnv('ENCRYPTION_KEY','c'.repeat(64));const original=Buffer.from('用户自己的书籍正文'),reference='用户甲/书籍甲';const cipher=sealFile(original,reference);expect(cipher.includes(original)).toBe(false);expect(openFile(cipher,reference)).toEqual(original);expect(()=>openFile(cipher,'用户乙/书籍乙')).toThrow();const tampered=Buffer.from(cipher);tampered[tampered.length-1]^=1;expect(()=>openFile(tampered,reference)).toThrow();vi.stubEnv('ENCRYPTION_KEY','d'.repeat(64));expect(()=>openFile(cipher,reference)).toThrow()});
 it('本地读写兼容且拒绝越界和云端位置误作本地路径',async()=>{const directory=await mkdtemp(join(tmpdir(),'reador-storage-'));vi.stubEnv('UPLOAD_DIR',directory);vi.stubEnv('STORAGE_BACKEND','local');try{const bytes=Buffer.from('正文'),reference=await writeStoredFile(randomUUID(),randomUUID(),'PDF',bytes);expect(await readStoredFile(reference)).toEqual(bytes);expect(()=>storagePath('../secret')).toThrow();expect(()=>storagePath('qiniu://bucket/key')).toThrow();await deleteStoredFile(reference);await expect(readStoredFile(reference)).rejects.toThrow()}finally{await rm(directory,{recursive:true,force:true})}});
 it.each(['s3','domain'])('七牛 %s 适配器只上传密文、读回原字节，拒绝换空间与损坏对象',async(mode)=>{vi.stubEnv('QINIU_DOWNLOAD_MODE',mode);for(const [name,value] of Object.entries({STORAGE_BACKEND:'qiniu',ENCRYPTION_KEY:'e'.repeat(64),QINIU_ACCESS_KEY:'test-ak',QINIU_SECRET_KEY:'test-sk',QINIU_BUCKET:'test-bucket',QINIU_DOMAIN:'https://files.example.com'}))vi.stubEnv(name,value);vi.stubGlobal('fetch',vi.fn(async(url:string)=>new Response(new Uint8Array(cloud.get(new URL(url).pathname.slice(1))!))));const original=Buffer.from('原书完整字节'),reference=await writeStoredFile(randomUUID(),randomUUID(),'EPUB',original),key=reference.split('/').slice(3).join('/');expect(cloud.get(key)?.includes(original)).toBe(false);expect(await readStoredFile(reference)).toEqual(original);await expect(readStoredFile(reference.replace('test-bucket','other-bucket'))).rejects.toThrow();const cipher=cloud.get(key)!;cipher[cipher.length-1]^=1;await expect(readStoredFile(reference)).rejects.toThrow();await deleteStoredFile(reference);expect(cloud.size).toBe(0)});
 it('服务器配置遵守账号策略，不回传原始密钥',()=>{vi.stubEnv('ENCRYPTION_KEY','f'.repeat(64));vi.stubEnv('ENV_MODEL_ACCESS','owner');vi.stubEnv('ENV_MODEL_OWNER_EMAIL','owner@example.com');vi.stubEnv('DEEPSEEK_API_KEY','SERVER_KEY_NOT_REAL');vi.stubEnv('DEEPSEEK_MODEL','test-model');vi.stubEnv('DEEPSEEK_BASE_URL','https://api.deepseek.com');vi.stubEnv('GLM_API_KEY','');expect(environmentModels('another@example.com')).toEqual([]);expect(()=>environmentAgent('another@example.com')).toThrow();const models=environmentModels('owner@example.com');expect(models).toHaveLength(1);expect(JSON.stringify(models)).not.toContain('SERVER_KEY');expect(environmentAgent('owner@example.com').keyCipher).not.toContain('SERVER_KEY');expect(environmentAgent('owner@example.com').maxTokens).toBe(1_000_000);vi.stubEnv('ENV_MODEL_ACCESS','disabled');expect(environmentModels('owner@example.com')).toEqual([]);vi.stubEnv('ENV_MODEL_ACCESS','shared');expect(environmentModels('another@example.com')).toHaveLength(1)});
});
