'use client';
import { useCallback,useEffect,useState,useRef } from 'react';
import { api,post,uid,errorText } from './api';
import type { User,Book,Agent,Review,Attempt,EnvironmentModel } from './types';
import type { Citation } from '../lib/schema';
import Settings from './Settings';
import BookCover from './BookCover';
import Reader from './Reader';
import GraphHub from './GraphHub';
import Study from './Study';
type View='home'|'library'|'reader'|'graph'|'reviews'|'settings';
const labels:Record<View,string>={home:'今日学习',library:'我的书库',reader:'阅读工作台',graph:'概念图谱',reviews:'复习计划',settings:'系统设置'};
export default function App(){
  const [user,setUser]=useState<User|null>(null),[ready,setReady]=useState(false),[view,setView]=useState<View>('home'),[bookId,setBookId]=useState(''),[sourceId,setSourceId]=useState<string|null>(null),[graphId,setGraphId]=useState<string|null>(null),[books,setBooks]=useState<Book[]>([]),[agents,setAgents]=useState<Agent[]>([]),[environment,setEnvironment]=useState<EnvironmentModel[]>([]),[reviews,setReviews]=useState<Review[]>([]),[attempts,setAttempts]=useState<Attempt[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[theme,setTheme]=useState('paper'),[study,setStudy]=useState<{card:Review;open:boolean;initialAttempt?:Attempt;assisted:boolean}|null>(null);
  const activeUser=useRef<string|null>(null);activeUser.current=user?.id||null;
  const refresh=useCallback(async()=>{const requester=activeUser.current;const [books,agents,reviews,attempts,environment]=await Promise.all([api<Book[]>('books'),api<Agent[]>('agents'),api<Review[]>('reviews'),api<Attempt[]>('attempts'),api<EnvironmentModel[]>('environment-models')]);if(!requester||requester!==activeUser.current)return;setBooks(books);setAgents(agents);setEnvironment(environment);setReviews(reviews);setAttempts(attempts)},[]);
  useEffect(()=>{void api<User>('auth/me').then(setUser).catch(()=>{}).finally(()=>setReady(true));const unauth=()=>{activeUser.current=null;setUser(null);setBooks([]);setAgents([]);setEnvironment([]);setReviews([]);setAttempts([]);setStudy(null)};window.addEventListener('reador:unauthorized',unauth);const route=()=>{const params=new URLSearchParams(location.search);const next=params.get('view') as View;if(next&&next in labels)setView(next);setBookId(params.get('book')||'');setSourceId(params.get('source'));setGraphId(params.get('graph'))};route();window.addEventListener('popstate',route);return()=>{window.removeEventListener('reador:unauthorized',unauth);window.removeEventListener('popstate',route)}},[]);
  useEffect(()=>{if(!user)return;let stopped=false;void refresh().catch(error=>setError(errorText(error)));const timer=setInterval(()=>{if(!stopped)void refresh().catch(()=>{})},5000);return()=>{stopped=true;clearInterval(timer)}},[user,refresh]);
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(timer)},[notice]);
  function navigate(next:View,id=bookId,source:string|null=null,graph:string|null=null){setView(next);setBookId(id);setSourceId(source);setGraphId(graph);setError('');if(next==='reader'&&study)setStudy({...study,open:false,assisted:true});const params=new URLSearchParams({view:next});if(id)params.set('book',id);if(source)params.set('source',source);if(next==='graph'&&graph)params.set('graph',graph);history.pushState(null,'','/?'+params);window.scrollTo({top:0})}
  async function generate(kind:string,chapterIds:string[]){if(!bookId)throw new Error('请先选择书籍');if(!agents.some(agent=>agent.isDefault)&&!environment.length)throw new Error('请先在系统设置中配置默认 Agent');await post('books/'+bookId+'/jobs',{kind,chapterIds,idempotencyKey:uid()});setNotice('任务已创建，可离开页面，进度会保存在服务端');await refresh()}
  async function uploadFile(file:File){setBusy(true);setError('');try{const form=new FormData();form.append('file',file);const book=await api<{id:string}>('books',{method:'POST',body:form});await refresh();navigate('library',book.id);setNotice('文件已保存，正在解析；重复文件会返回已有书籍')}catch(error){setError(errorText(error))}finally{setBusy(false)}}
  async function openStudy(card:Review,initialAttempt?:Attempt){try{const attempt=initialAttempt||await post<Attempt>('cards/'+card.id+'/start',{idempotencyKey:uid()});setStudy({card,open:true,initialAttempt:attempt,assisted:attempt.assisted})}catch(error){setError(errorText(error))}}
  const citation=useCallback((value:Citation)=>{navigate('reader',bookId,value.sourceId)},[bookId,study]);
  function formatDate(value:string){return new Intl.DateTimeFormat('zh-CN',{timeZone:user?.timezone||'Asia/Shanghai',month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value))}
  if(!ready)return <div className="loading">正在打开 Reador…</div>;
  if(!user)return <Auth onLogin={value=>{activeUser.current=value.id;setUser(value);setError('')}}/>;
  const due=reviews.filter(card=>card.due),selectedBooks=books.filter(book=>(!bookId||book.id===bookId)&&book.title.toLowerCase().includes(query.toLowerCase()));
  const filteredReviews=reviews.filter(card=>!bookId||card.bookId===bookId);
  const pending=attempts.filter(attempt=>!attempt.ratedAt&&(attempt.kind!=='remedy'||!attempt.assessment));
  return <div className="shell" data-theme={theme}><a className="skip" href="#main">跳到主要内容</a><aside className="sidebar"><button className="logo" onClick={()=>navigate('home','')}>reador<span>.</span></button><p className="tagline">读有所获，学有所记</p><nav aria-label="主要导航">{(['home','library','graph','reviews','settings'] as View[]).map(id=><button key={id} aria-current={view===id?'page':undefined} onClick={()=>navigate(id,id==='reviews'?'':bookId)}>{labels[id]}{id==='reviews'&&due.length>0&&<span className="badge">{due.length}</span>}</button>)}</nav><div className="side-note"><p>一点一点，<br/>读进自己的世界。</p><small>{user.name} · 私人阅读空间</small><button className="text" onClick={()=>void post('auth/logout').then(()=>{activeUser.current=null;setUser(null);setStudy(null);setBooks([]);setAgents([]);setEnvironment([]);setReviews([]);setAttempts([])})}>退出登录</button></div></aside>
    <main id="main"><header className="topbar"><span className="muted">我的空间 / {labels[view]}</span><div className="row"><select aria-label="外观" value={theme} onChange={event=>setTheme(event.target.value)}><option value="paper">纸感书房</option><option value="plain">简洁工具</option><option value="night">深色专注</option></select><label className={'upload-button '+(busy?'disabled':'')}>{busy?'上传中…':'＋ 导入书籍'}<input type="file" accept=".pdf,.epub" disabled={busy} onChange={event=>{const file=event.target.files?.[0];if(file)void uploadFile(file);event.target.value=''}}/></label></div></header><div className="content">
    {error&&<p className="error" role="alert">{error}</p>}
    {view==='home'&&<><div className="intro"><p className="eyebrow">A LITTLE EVERY DAY</p><h1>{user.name}，今天也读一点。</h1><p className="muted">从原文开始，用回忆留下理解。</p></div><div className="home-grid"><section className="panel"><span className="eyebrow">继续阅读</span><h2>{books.find(book=>book.status==='ready')?.title||'你的第一本书，从这里开始。'}</h2><p className="muted">{books.length?'阅读位置与学习记录会保存在当前账号下。':'导入 PDF 或 EPUB，建立自己的阅读与复习计划。'}</p><button onClick={()=>{const book=books.find(book=>book.status==='ready');navigate(book?'reader':'library',book?.id||'')}}>{books.some(book=>book.status==='ready')?'继续阅读 →':'打开书库 →'}</button></section><section className="panel tint"><span className="eyebrow">到期复习</span><div className="big-count">{due.length}<small>个知识目标</small></div><p className="muted">先独立回忆，再核对答案与原文。</p><button onClick={()=>navigate('reviews','')}>查看复习计划 →</button></section></div><div className="panel"><div className="row spread"><h2>学习足迹</h2><span className="muted">真实记录</span></div><div className="stats"><p><strong>{books.length}</strong>本书</p><p><strong>{reviews.length}</strong>个复习目标</p><p><strong>{attempts.length}</strong>次最近作答</p><p><strong>{pending.length}</strong>次待评分 / 待评级</p></div><button className="text" onClick={()=>navigate('reviews','')}>继续未完成的学习 →</button></div>{!agents.some(agent=>agent.isDefault)&&!environment.length&&<p className="notice">开始 AI 学习前，请配置默认模型。<button className="text" onClick={()=>navigate('settings')}>前往系统设置 →</button></p>}</>}
    {view==='library'&&<><div className="intro"><p className="eyebrow">YOUR PRIVATE LIBRARY</p><h1>把想读的书，放在身边。</h1><p className="muted">{books.length} 本书 · PDF / EPUB · 原始文件仅当前账号可访问</p><p className="muted small">解析后自动显示书内封面，PDF 使用首页缩略图。AI 总结、图谱与练习按原文分批处理。</p></div><label className="search-label">搜索书籍<input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="输入书名"/></label><div className="book-grid">{books.filter(book=>book.title.toLowerCase().includes(query.toLowerCase())).map(book=><article className="book-tile" key={book.id}><BookCover book={book} onRead={()=>navigate('reader',book.id)}/><div className="book-body"><span className="badge">{{queued:'等待解析',parsing:'正在解析',ready:'可阅读',failed:'解析失败'}[book.status]||book.status}</span><h3 title={book.title}>{book.title}</h3><p>{book.cards} 个复习目标 · {book.due} 个到期</p>{book.error&&<p className="error">{book.error}</p>}<div className="book-actions"><button disabled={book.status!=='ready'} onClick={()=>navigate('reader',book.id)}>继续阅读 →</button><button className="text" disabled={book.status!=='ready'} onClick={()=>navigate('graph',book.id)}>概念图谱 →</button><button className="text" onClick={()=>navigate('reviews',book.id)}>查看复习计划 →</button>{book.status==='failed'&&<button className="text" onClick={()=>void api<{id:string;kind:string}[]>('books/'+book.id+'/jobs').then(async jobs=>{const job=jobs.find(job=>job.kind==='parse');if(job)await post('jobs/'+job.id+'/retry');await refresh()}).catch(error=>setError(errorText(error)))}>重新解析</button>}</div></div></article>)}<label className="book-add"><strong>＋</strong><h3>下一本，想读什么？</h3><p>添加一本书，开始新的阅读。</p><small>PDF / EPUB · 最大 50 MB</small><input type="file" accept=".pdf,.epub" disabled={busy} onChange={event=>{if(event.target.files?.[0])void uploadFile(event.target.files[0]);event.target.value=''}}/></label></div></>}
    {view==='reader'&&(bookId?<Reader key={bookId} bookId={bookId} sourceId={sourceId} onCitation={citation} onGenerate={generate} onSettings={()=>navigate('settings')} onStudy={()=>navigate('reviews',bookId)}/>:<p className="empty">请先从书库选择一本已解析的书籍。</p>)}
    {view==='graph'&&<GraphHub key={bookId} books={books} bookId={bookId} detailId={graphId} timezone={user.timezone} onOpen={id=>navigate('graph',bookId,null,id)} onBook={id=>navigate('graph',id)} onCitation={citation} onGenerate={generate}/>}
    {view==='reviews'&&<><div className="intro"><p className="eyebrow">MAKE IT STICK</p><h1>在忘记之前，再遇见一次。</h1><p className="muted">按书籍查看复习目标 · FSRS 排期 · {user.timezone}</p></div><div className="panel row spread"><label>按书籍查看<select value={bookId} onChange={event=>navigate('reviews',event.target.value)}><option value="">全部书籍</option>{books.map(book=><option key={book.id} value={book.id}>{book.title}</option>)}</select></label><p>{filteredReviews.filter(card=>card.due).length} 个到期 · {filteredReviews.filter(card=>!card.due).length} 个后续复习</p><button disabled={!filteredReviews.some(card=>card.due)} onClick={()=>openStudy(filteredReviews.find(card=>card.due)!)}>开始到期复习 →</button></div>
      {pending.filter(attempt=>!bookId||attempt.bookId===bookId).length>0&&<section className="panel"><h2>继续未完成的作答</h2>{pending.filter(attempt=>!bookId||attempt.bookId===bookId).map(attempt=><button className="topic" key={attempt.id} onClick={()=>{const card=reviews.find(card=>card.id===attempt.cardId);if(card)openStudy(card,attempt)}}><span>{books.find(book=>book.id===attempt.bookId)?.title} · {attempt.assessment?'待确认评级':attempt.answer?'答案已保存，待评分':'待继续作答'}</span><small>{formatDate(attempt.createdAt)} →</small></button>)}</section>}
      {selectedBooks.map(book=><section className="panel" key={book.id}><div className="row spread"><h2>{book.title}</h2><button className="text" disabled={book.status!=='ready'} onClick={()=>navigate('reader',book.id)}>回到阅读 →</button></div>{!filteredReviews.some(card=>card.bookId===book.id)&&<p className="empty">{book.status==='ready'?'暂无复习卡。进入阅读工作台，生成本章练习后开始学习。':'等待解析完成后才能建立本书的复习任务。'}</p>}{filteredReviews.filter(card=>card.bookId===book.id).map(card=><button className="topic" disabled={!card.due} key={card.id} onClick={()=>openStudy(card)}><span>{card.question.goal}<small>{card.version?'已完成 '+card.version+' 次评级':'尚未开始'}</small></span><small>{card.due?'已到期 →':'下次：'+formatDate(card.dueAt)}</small></button>)}</section>)}{!books.length&&<p className="empty">先导入一本书，复习计划会随学习逐步建立。</p>}
      {attempts.filter(attempt=>attempt.ratedAt||attempt.kind==='remedy').length>0&&<section className="panel"><h2>最近学习记录</h2>{attempts.filter(attempt=>(!bookId||attempt.bookId===bookId)&&(attempt.ratedAt||attempt.kind==='remedy')).slice(0,20).map(attempt=><article className="history" key={attempt.id}><strong>{books.find(book=>book.id===attempt.bookId)?.title}</strong><p>{attempt.kind==='remedy'?'即时补救练习':'正式学习 / 复习'} · {attempt.assisted?'辅助作答':'独立作答'} · {attempt.assessment?.score??'待评分'} 分 · {formatDate(attempt.createdAt)}</p><details><summary>查看作答与反馈</summary><p>{attempt.answer}</p><p>{attempt.assessment?.feedback}</p></details></article>)}</section>}
    </>}
    {view==='settings'&&<Settings agents={agents} environment={environment} user={user} reload={refresh} onUser={setUser}/>}
    <footer><span>Reador · 围绕原文理解与记忆</span><small>学习数据仅属于当前账号</small></footer>
    </div></main>{notice&&<div className="toast" role="status">{notice}</div>}
    {study&&<Study key={study.card.id+(study.initialAttempt?.id||'')} card={study.card} open={study.open} initialAttempt={study.initialAttempt} assistance={study.assisted} onClose={()=>setStudy(previous=>previous?{...previous,open:false}:null)} onRated={refresh} onCitation={value=>navigate('reader',study.card.bookId,value.sourceId)}/>}
  </div>;
}
function Auth({onLogin}:{onLogin:(user:User)=>void}){const [register,setRegister]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');return <main className="auth-page"><section className="auth-story"><div className="logo">reador<span>.</span></div><p className="eyebrow">READ · UNDERSTAND · REMEMBER</p><h1>不止读过，<br/>也真正记得。</h1><p>从书中的一段话，到自己的理解。<br/>用主动回忆与间隔复习，留住每一次收获。</p><small>原文阅读 / AI 辅助理解 / 持续复习</small></section><section className="auth-form panel"><p className="eyebrow">YOUR PRIVATE READING SPACE</p><h2>{register?'开启你的阅读空间':'欢迎回来。'}</h2><p className="muted">每个账号独立保存书籍、模型配置与学习记录。</p><form onSubmit={event=>{event.preventDefault();setBusy(true);setError('');void post<User>('auth/'+(register?'register':'login'),{email,password,...(register?{name}:{})}).then(onLogin).catch(error=>setError(errorText(error))).finally(()=>setBusy(false))}}>{register&&<label>昵称<input required value={name} maxLength={80} autoComplete="nickname" onChange={event=>setName(event.target.value)}/></label>}<label>邮箱<input type="email" required value={email} autoComplete="username" onChange={event=>setEmail(event.target.value)}/></label><label>密码<input type="password" required minLength={12} maxLength={128} value={password} autoComplete={register?'new-password':'current-password'} onChange={event=>setPassword(event.target.value)}/><small>至少 12 个字符。</small></label>{error&&<p className="error" role="alert">{error}</p>}<button disabled={busy}>{busy?'正在处理…':register?'注册并进入':'登录'}</button></form><button className="text" disabled={busy} onClick={()=>{setRegister(!register);setError('');setPassword('')}}>{register?'已有账号？去登录 →':'还没有账号？创建账号 →'}</button><p className="muted small">当前本地版提供邮箱密码注册登录，暂不包含邮件验证或找回密码。</p></section></main>}
