'use client';
import { useEffect,useRef,useState } from 'react';
import { api,post,put,uid,errorText } from './api';
import type { Book,Chapter,Source,Job,Artifact } from './types';
import type { Citation } from '../lib/schema';
import Graph from './Graph';
import { graphSchema,summarySchema } from '../modules/ai/validation';
type Detail=Book&{chapters:Chapter[];progress:{chapterId:string;sourceId:string|null}|null};
type Message={id:string;question:string;answer:string;mode:string;citations:Citation[];insufficient:boolean};
type Conversation={id:string;chapterId:string|null;selectedSourceId:string|null;messages?:Message[]};
export default function Reader({bookId,sourceId,tab='read',onCitation,onGenerate,onSettings,onStudy}:{bookId:string;sourceId:string|null;tab?:string;onCitation:(citation:Citation)=>void;onGenerate:(kind:string,chapterIds:string[])=>Promise<void>;onSettings:()=>void;onStudy:()=>void}){
  const [book,setBook]=useState<Detail|null>(null),[chapterId,setChapterId]=useState(''),[text,setText]=useState<Source[]>([]),[textLoading,setTextLoading]=useState(false),[error,setError]=useState(''),[activeTab,setActiveTab]=useState(tab),[artifacts,setArtifacts]=useState<Artifact[]>([]),[jobs,setJobs]=useState<Job[]>([]),[question,setQuestion]=useState(''),[busy,setBusy]=useState(false),[mode,setMode]=useState('qa'),[scope,setScope]=useState('chapter'),[selected,setSelected]=useState<string|null>(null),[conversation,setConversation]=useState<Conversation|null>(null),[messages,setMessages]=useState<Message[]>([]),[conversationHistory,setConversationHistory]=useState<Conversation[]>([]),[part,setPart]=useState(0);
  const contextVersion=useRef(0),messageKey=useRef(uid());
  useEffect(()=>{setActiveTab(tab)},[tab]);
  useEffect(()=>{let cancelled=false;void api<Detail>('books/'+bookId).then(async entry=>{if(cancelled)return;setBook(entry);let chapter=entry.progress?.chapterId||entry.chapters[0]?.id||'';if(sourceId){const source=await api<Source>('sources/'+sourceId);if(source.bookId===bookId)chapter=source.chapterId;}if(!cancelled)setChapterId(chapter)}).catch(error=>setError(errorText(error)));return()=>{cancelled=true}},[bookId,sourceId]);
  useEffect(()=>{if(!chapterId)return;let cancelled=false;setSelected(null);setText([]);setTextLoading(true);void api<Source[]>('books/'+bookId+'/sources?chapterId='+chapterId).then(rows=>{if(!cancelled){setText(rows);setTextLoading(false)}}).catch(error=>setError(errorText(error)));void put('books/'+bookId+'/progress',{chapterId,sourceId:null}).catch(error=>setError(errorText(error)));return()=>{cancelled=true}},[bookId,chapterId]);
  useEffect(()=>{if(!text.length||!sourceId)return;const block=document.getElementById('source-'+sourceId);block?.scrollIntoView({behavior:'smooth',block:'center'});block?.focus()},[text,sourceId]);
  useEffect(()=>{let stopped=false;const refresh=async()=>{try{const [data,status]=await Promise.all([api<Artifact[]>('books/'+bookId+'/artifacts'),api<Job[]>('books/'+bookId+'/jobs')]);if(!stopped){setArtifacts(data);setJobs(status)}}catch(error){if(!stopped)setError(errorText(error))}};void refresh();const timer=setInterval(()=>void refresh(),4000);return()=>{stopped=true;clearInterval(timer)}},[bookId]);
  useEffect(()=>{if(!chapterId)return;let stopped=false;contextVersion.current++;setConversation(null);setMessages([]);messageKey.current=uid();const target=scope==='book'?null:chapterId;const chosen=scope==='selection'?selected:null;
    void api<Conversation[]>('conversations?bookId='+bookId).then(async list=>{if(stopped)return;setConversationHistory(list);const old=list.find(item=>item.chapterId===target&&item.selectedSourceId===chosen);if(old){const existing=await api<Conversation>('conversations/'+old.id);if(!stopped){setConversation(existing);setMessages(existing.messages||[])}}}).catch(error=>setError(errorText(error)));return()=>{stopped=true};
  },[bookId,chapterId,scope,selected]);
  useEffect(()=>{
    if(!book||book.structureVersion>0||!jobs.some(job=>job.kind==='structure'&&job.status==='ready'))return;
    let stopped=false;void api<Detail>('books/'+bookId).then(entry=>{if(!stopped){setBook(entry);setChapterId(entry.progress?.chapterId||entry.chapters[0]?.id||'')}}).catch(error=>setError(errorText(error)));return()=>{stopped=true};
  },[book,bookId,jobs]);
  async function ask(event:React.FormEvent){event.preventDefault();if(!conversation&&scope==='selection'&&!selected){setError('请先在原文中选择一段');return}setBusy(true);setError('');const version=contextVersion.current;try{let current=conversation;if(!current){current=await post<Conversation>('conversations',{bookId,chapterId:scope==='book'?null:chapterId,selectedSourceId:scope==='selection'?selected:null});if(version===contextVersion.current){setConversation(current);setConversationHistory(previous=>[current!,...previous])}}const reply=await post<Message>('conversations/'+current.id+'/messages',{question,mode,idempotencyKey:messageKey.current});if(version===contextVersion.current){setMessages(previous=>[...previous,reply]);setQuestion('');messageKey.current=uid()}}catch(error){setError(errorText(error))}finally{setBusy(false)}}
  const kind=activeTab==='graph'?'graph':'summary';const artifact=artifacts.find(item=>item.kind===kind&&(item.data as {data:unknown}[]).some(batch=>{const data=batch.data as {nodes?:{citations:Citation[]}[];items?:{citations:Citation[]}[]};return [...(data.nodes||[]),...(data.items||[])].some(item=>item.citations.some(citation=>text.some(source=>source.id===citation.sourceId)))}));
  const batches=artifact?(artifact.data as {batch:number;data:unknown}[]).filter(batch=>{const data=batch.data as {nodes?:{citations:Citation[]}[];items?:{citations:Citation[]}[]};return [...(data.nodes||[]),...(data.items||[])].some(item=>item.citations.some(citation=>text.some(source=>source.id===citation.sourceId)))}):[];
  const current=batches[Math.min(part,Math.max(0,batches.length-1))];
  return <><div className="intro"><p className="eyebrow">READ · UNDERSTAND · REMEMBER</p><h1>{book?.title||'载入书籍…'}</h1><p className="muted">原书保持不变 · AI 解释与来源可以逐项核对</p></div>{error&&<p className="error" role="alert">{error} <button className="text" onClick={onSettings}>检查 Agent 设置 →</button></p>}
    <div className="reader-grid"><aside className="panel catalog"><h2>阅读目录</h2><p className="muted small">{book?.chapters.some(chapter=>chapter.origin==='toc')?'已读取原书目录':book?.chapters.some(chapter=>chapter.origin==='outline')?'已读取 PDF 书签目录':'未读取到可靠目录，按正文结构分节'}</p>{book?.structureVersion===0&&<button className="outline" disabled={jobs.some(job=>job.kind==='structure'&&['queued','running'].includes(job.status))} onClick={()=>{setError('');void post('books/'+bookId+'/structure').then(()=>api<Job[]>('books/'+bookId+'/jobs')).then(setJobs).catch(error=>setError(errorText(error)))}}>更新原书目录</button>}<a className="small" href={"/api/books/"+bookId+"/file"}>下载原书</a>{book?.chapters.map(chapter=><button key={chapter.id} className={'chapter '+(chapter.id===chapterId?'active':'')} style={{paddingLeft:14+Math.min(chapter.depth,4)*12}} onClick={()=>{setChapterId(chapter.id);setPart(0)}}>{chapter.title}{!['toc','outline'].includes(chapter.origin)&&<small>{{page:'按实际页码分段',heading:'按正文标题分节',file:'按文件分节',legacy:'旧版分节 · 可更新目录'}[chapter.origin]||'推断分节'} · 非原书目录</small>}</button>)}<button className="outline" onClick={onStudy}>本书复习计划 →</button></aside>
    <section className="panel prose"><div className="row spread"><h2>{book?.chapters.find(item=>item.id===chapterId)?.title}</h2><span className="muted small">{text.length} 个原文片段</span></div>{!text.length&&<p className="empty">{textLoading?'正在载入原文…':'本节未提取到正文，可能为空白页或扫描内容；当前不支持 OCR。'}</p>}{text.map(source=><article id={'source-'+source.id} tabIndex={-1} key={source.id} className={'source '+(source.id===sourceId||source.id===selected?'selected':'')}><small>{source.locator.page?'实际页码 '+source.locator.page:'段落 '+source.locator.paragraph} · 片段 {source.position+1}</small><p>{source.text}</p><button className="text" onClick={()=>{setSelected(source.id);setScope('selection');setActiveTab('chat');setMode('explain');setQuestion('请解释这段原文');void put('books/'+bookId+'/progress',{chapterId,sourceId:source.id})}}>解释本段</button><button className="text" onClick={()=>{setSelected(source.id);setScope('selection');setActiveTab('chat');setMode('diagnose');setQuestion('引导我理解这段原文')}}>引导我理解</button></article>)}</section>
    <aside className="panel reader-tools"><div className="tabs">{[['read','学习'],['summary','总结'],['graph','图谱'],['chat','问答 / 教学']].map(([id,label])=><button key={id} aria-pressed={activeTab===id} onClick={()=>{setActiveTab(id);setPart(0)}}>{label}</button>)}</div>
      {activeTab==='read'&&<><h2>读过之后，试着说出来。</h2><p className="muted">为当前章生成练习，答案会在作答后显示。出题会将本章原文发送给默认模型。</p><button disabled={busy||!chapterId} onClick={()=>{setBusy(true);void onGenerate('questions',[chapterId]).catch(error=>setError(errorText(error))).finally(()=>setBusy(false))}}>生成本章练习 →</button><button className="outline" onClick={onStudy}>查看本书复习计划</button><p className="notice">练习按独立知识目标建卡。请先查看已有复习卡，避免重复生成相同内容。</p></>}
      {(activeTab==='summary'||activeTab==='graph')&&<><div className="row spread"><h2>{kind==='graph'?'本章概念图':'本章总结'}</h2><button disabled={busy||!chapterId} onClick={()=>{setBusy(true);void onGenerate(kind,[chapterId]).catch(error=>setError(errorText(error))).finally(()=>setBusy(false))}}>生成新版本</button></div><p className="muted small">按批次展示实际覆盖的原文；新版本保留旧记录。此操作发送本章原文给模型。</p>{batches.length>1&&<label>原文批次<select value={Math.min(part,batches.length-1)} onChange={event=>setPart(Number(event.target.value))}>{batches.map((item,index)=><option key={item.batch} value={index}>第 {item.batch+1} 批</option>)}</select></label>}
        {!current?<p className="empty">尚无本章结果，先生成一版。</p>:kind==='graph'?<Graph key={artifact?.id+'-'+current.batch} graph={graphSchema.parse(current.data)} onCitation={onCitation}/>:<div className="summaries">{summarySchema.parse(current.data).items.map((item,index)=><article key={index}><h3>{item.title}</h3><p>{item.text}</p>{item.citations.map((citation,j)=><button key={j} className="citation" onClick={()=>onCitation(citation)}>“{citation.quote}” · 原文 →</button>)}</article>)}</div>}
      </>}
      {activeTab==='chat'&&<><h2>与原文一起思考。</h2><div className="fields"><label>引用范围<select disabled={busy} value={scope} onChange={event=>setScope(event.target.value)}><option value="chapter">当前章</option><option value="selection" disabled={!selected}>所选原文片段</option><option value="book">整本书（主动扩大）</option></select></label><label>学习方式<select value={mode} onChange={event=>setMode(event.target.value)}><option value="qa">问答</option><option value="diagnose">引导诊断</option><option value="hint">逐步提示</option><option value="explain">直接讲解</option><option value="check">检查理解</option></select></label></div><p className="muted small">长章或整书按问题检索相关片段；证据不足时不会自动扩大范围。</p>{conversationHistory.length>0&&<label>历史问答<select disabled={busy} value={conversation?.id||''} onChange={event=>{const version=++contextVersion.current;messageKey.current=uid();setConversation(null);setMessages([]);if(!event.target.value)return;setBusy(true);void api<Conversation>('conversations/'+event.target.value).then(entry=>{if(version===contextVersion.current){setConversation(entry);setMessages(entry.messages||[])}}).catch(error=>{if(version===contextVersion.current)setError(errorText(error))}).finally(()=>setBusy(false))}}><option value="">开始当前范围的新会话</option>{conversationHistory.map((entry,index)=><option key={entry.id} value={entry.id}>会话 {index+1} · {entry.selectedSourceId?'选段 · ':''}{entry.chapterId?(book?.chapters.find(chapter=>chapter.id===entry.chapterId)?.title||'目录更新前的章节'):'全书'}</option>)}</select></label>}{conversation&&<p className="notice">本会话实际引用范围：{conversation.selectedSourceId?'一个已选原文片段':conversation.chapterId?(book?.chapters.find(chapter=>chapter.id===conversation.chapterId)?.title||'目录更新前的章节（保留原范围）'):'全书'}。切换上方引用范围可返回当前阅读上下文。</p>}<div className="chat-messages">{messages.map(message=><article key={message.id}><p className="chat-question">{message.question}</p><p>{message.answer}</p>{message.insufficient&&<span className="badge">当前证据不足</span>}{message.citations.map((citation,index)=><button key={index} className="citation" onClick={()=>onCitation(citation)}>“{citation.quote}” · 核对原文 →</button>)}</article>)}</div><form onSubmit={ask}><label>问题或你的理解<textarea required rows={3} value={question} maxLength={4000} onChange={event=>{setQuestion(event.target.value);messageKey.current=uid()}}/></label><button disabled={busy||!chapterId}>{busy?'正在思考…':'发送'}</button></form></>}
      {jobs.filter(job=>job.kind!=='parse'&&job.kind!=='graph'&&job.status!=='ready').slice(0,4).map(job=><div className="notice" key={job.id}><strong>{{graph:'概念图',summary:'总结',questions:'出题',cover:'提取封面',structure:'更新目录'}[job.kind]||job.kind} · {job.status}</strong>{['cover','structure'].includes(job.kind)?<p>{job.kind==='cover'?'正在读取书内封面':'正在核对原文并更新目录'}，不发送给模型。</p>:<p>{job.completed} / {job.total} 批完成</p>}{job.errors.map((error,index)=><p key={index}>{error.message}</p>)}{['failed','partial'].includes(job.status)&&<button className="text" onClick={()=>void post('jobs/'+job.id+'/retry').catch(error=>setError(errorText(error)))}>{['cover','structure'].includes(job.kind)?'重试任务':'重试失败批次'}</button>}{['queued','running'].includes(job.status)&&<button className="text" onClick={()=>void post('jobs/'+job.id+'/cancel').catch(error=>setError(errorText(error)))}>取消任务</button>}</div>)}
    </aside></div>
  </>;
}
