'use client';
import { useState } from 'react';
import { api,post,put,errorText } from './api';
import type { Agent,User,EnvironmentModel } from './types';
import { presets,providerDefaults,MODEL_PRESETS_CHECKED_AT,DEFAULT_MAX_OUTPUT_TOKENS,modelOutputLimit,effectiveMaxOutputTokens } from '../modules/ai/presets';
const blank=()=>({name:'',...providerDefaults('deepseek'),timeout:60,retries:1,temperature:'',isDefault:true});
export default function Settings({agents,environment,user,reload,onUser}:{agents:Agent[];environment:EnvironmentModel[];user:User;reload:()=>Promise<void>;onUser:(user:User)=>void}){
  const [form,setForm]=useState(blank),[editing,setEditing]=useState<string|null>(null),[busy,setBusy]=useState(false),[show,setShow]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[timezone,setTimezone]=useState(user.timezone);
  const patch=(value:Partial<ReturnType<typeof blank>>)=>{setForm(previous=>({...previous,...value}));setError('');setStatus('有未保存的修改')};
  const reset=()=>{setForm({...blank(),isDefault:!agents.some(agent=>agent.isDefault)});setEditing(null);setShow(false);setStatus('');setError('')};
  // 从已保存配置切换默认项时，只提交可编辑字段，避免携带服务端返回的元数据。
  const payload=(value:ReturnType<typeof blank>)=>({name:value.name,provider:value.provider,route:value.route,protocol:value.protocol,baseUrl:value.baseUrl,model:value.model,apiKey:value.apiKey||undefined,timeout:value.timeout,retries:value.retries,maxTokens:value.maxTokens,temperature:value.temperature===''?null:Number(value.temperature),isDefault:value.isDefault});
  async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{const saved=editing?await put<Agent>('agents/'+editing,payload(form)):await post<Agent>('agents',payload(form));setEditing(saved.id);setForm(previous=>({...previous,apiKey:''}));setShow(false);setStatus('已保存。API Key 已由服务端加密保存，不会回传。');await reload()}catch(error){setError(errorText(error))}finally{setBusy(false)}}
  async function run(operation:()=>Promise<unknown>,message:string){setBusy(true);setError('');try{await operation();setStatus(message);await reload();return true}catch(error){setError(errorText(error));return false}finally{setBusy(false)}}
  function edit(agent:Agent){setEditing(agent.id);setForm({name:agent.name,provider:agent.provider,route:agent.route,protocol:agent.protocol,baseUrl:agent.baseUrl,model:agent.model,apiKey:'',timeout:agent.timeout,retries:agent.retries,maxTokens:agent.maxTokens,temperature:agent.temperature||'',isDefault:agent.isDefault});setShow(false);setError('');setStatus('留空 API Key 可保留原密钥，更换地址时需重新填写。')}
  return <><div className="intro"><p className="eyebrow">YOUR READING AGENT</p><h1>让 Agent，连接你的模型。</h1><p className="muted">系统设置 / 仅管理当前账号的模型配置</p></div>
    <p className="notice">AI 功能会将你选择范围内的书籍片段与作答发送给配置的模型服务。连接测试只发送最小测试消息。请核对第三方服务地址与数据使用政策。</p>
    {environment.length>0&&<section className="panel"><h2>服务器模型</h2><p className="muted">来自服务端环境配置；没有个人默认 Agent 时自动使用系统默认项，凭据不会回传。</p>{environment.map(model=><article className="profile" key={model.provider}><h3>{model.name} {model.isDefault&&<span className="badge">系统默认</span>}</h3><p>{model.model}</p><div className="row"><button className="text" disabled={busy} onClick={()=>run(()=>post('environment-models/'+model.provider+'/test'),'真实连接测试成功')}>测试连接</button><button className="text" disabled={busy} onClick={()=>run(()=>post('environment-models/'+model.provider+'/import'),'已另存为个人默认配置；后续修改独立保存')}>另存为个人默认配置</button></div></article>)}{error&&<p className="error" role="alert">{error}</p>}<p className="status" role="status">{status}</p></section>}
    <div className="settings-grid"><aside className="panel"><div className="row spread"><h2>我的配置</h2><button className="text" onClick={reset}>＋ 新建</button></div>{!agents.length&&<p className="empty">先添加 DeepSeek 或 GLM，即可开始生成与学习。</p>}{agents.map(agent=><article className="profile" key={agent.id}><h3>{agent.name} {agent.isDefault&&<span className="badge">默认</span>}</h3><p>{presets[agent.provider as keyof typeof presets]?.name||agent.provider} / {agent.model}</p><small>{agent.protocol} · {agent.hasKey?'密钥已配置':'缺少密钥'}</small><p className="muted wrap">{agent.baseUrl}</p><div className="row"><button className="text" disabled={busy} onClick={()=>edit(agent)}>编辑</button><button className="text" disabled={busy||agent.isDefault} onClick={()=>run(()=>put('agents/'+agent.id,payload({...blank(),...agent,apiKey:'',temperature:agent.temperature||'',isDefault:true})), '默认 Agent 已更新')}>设为默认</button><button className="text" disabled={busy} onClick={()=>run(()=>post('agents/'+agent.id+'/test'),'真实连接测试成功')}>测试连接</button><button className="text" disabled={busy} onClick={()=>{if(confirm('删除这组模型配置？不会删除书籍或学习历史。'))void run(()=>api('agents/'+agent.id,{method:'DELETE'}),'配置已删除').then(saved=>{if(saved&&editing===agent.id)reset()})}}>删除</button></div></article>)}</aside>
    <form className="panel" onSubmit={save}><div className="row spread"><h2>{editing?'编辑 Agent 配置':'新建 Agent 配置'}</h2><span className="badge">服务端加密凭据</span></div>
      <fieldset disabled={busy}><div className="fields">
      <label className="wide">配置名称<input required maxLength={80} value={form.name} onChange={event=>patch({name:event.target.value})}/></label>
      <label>模型厂商<select value={form.provider} onChange={event=>{const provider=event.target.value as keyof typeof presets;patch(providerDefaults(provider));setShow(false)}}>{Object.entries(presets).map(([id,preset])=><option key={id} value={id}>{preset.name}</option>)}</select></label>
      <label>接入方式<select value={form.route} onChange={event=>patch({route:event.target.value,baseUrl:event.target.value==='official'?presets[form.provider as keyof typeof presets].baseUrl:'',model:event.target.value==='official'?presets[form.provider as keyof typeof presets].model:'',apiKey:''})}><option value="official" disabled={form.provider==='custom'}>官方 API</option><option value="third-party">第三方 / 自建网关</option></select></label>
      <label className="wide">API 协议<select value={form.protocol} onChange={event=>patch({protocol:event.target.value})}><option value="chat">OpenAI Chat Completions · /chat/completions</option><option value="responses">OpenAI Responses · /responses</option><option value="messages">Anthropic Messages · /messages</option></select><small>根据服务商文档选择；相同厂商的不同接口需要分别支持。</small></label>
      <label className="wide">Base URL<input type="url" required maxLength={500} readOnly={form.route==='official'} value={form.baseUrl} onChange={event=>patch({baseUrl:event.target.value})}/><small>填写 API 前缀，可含 /v1；不包含末尾接口路径。</small></label>
      <p className="notice wide wrap">请求地址：{form.baseUrl.replace(/\/+$/,'')+({chat:'/chat/completions',responses:'/responses',messages:'/messages'}[form.protocol]||'')}</p>
      <label className="wide">模型 ID<input required value={form.model} maxLength={160} placeholder="填写控制台可用的模型 ID" onChange={event=>patch({model:event.target.value})}/><small>{form.provider==='custom'||form.route==='third-party'?'请填写当前网关实际可用的模型别名。':<>默认使用截至 {MODEL_PRESETS_CHECKED_AT} 核对的官方通用模型，可按账号权限修改。<a href={presets[form.provider as keyof typeof presets].docsUrl} target="_blank" rel="noreferrer">查看官方模型说明</a></>}</small></label>
      <label className="wide">API Key<div className="key-input"><input required={!editing} type={show?'text':'password'} value={form.apiKey} maxLength={512} autoComplete="off" placeholder={editing?'留空保留已有密钥':'填写此接入方式的 API Key'} onChange={event=>patch({apiKey:event.target.value})}/><button type="button" className="outline" aria-pressed={show} onClick={()=>setShow(!show)}>{show?'隐藏':'显示'}</button></div><small>仅提交给 Reador 服务端。修改地址时需重新填写凭据。</small></label>
      <label>请求超时（秒）<input type="number" min={5} max={300} required value={form.timeout} onChange={event=>patch({timeout:Number(event.target.value)})}/></label>
      <label>最大重试次数<input type="number" min={0} max={3} required value={form.retries} onChange={event=>patch({retries:Number(event.target.value)})}/></label>
      <label>期望最大输出 tokens<input type="number" min={256} max={DEFAULT_MAX_OUTPUT_TOKENS} required value={form.maxTokens} onChange={event=>patch({maxTokens:Number(event.target.value)})}/><small>默认 1,000,000（1M），是单次回答的上限；上下文窗口包含输入与输出，由模型决定。提高此值不会扩大书籍分批范围，也不会要求模型写满。</small>{modelOutputLimit(form.baseUrl,form.model)!==undefined?<small>按已核实的官方模型限制，本配置实际发送上限：{effectiveMaxOutputTokens(form).toLocaleString('zh-CN')} tokens。</small>:<small>此型号或网关的输出限制尚未核实，将按填写值发送；请按服务商文档调整，超过其上限可能被拒绝。</small>}<button type="button" className="text" onClick={()=>patch({maxTokens:DEFAULT_MAX_OUTPUT_TOKENS})}>使用 1M 默认值</button></label>
      <label>Temperature（可选）<input type="number" min={0} max={2} step={0.1} value={form.temperature} placeholder="留空使用模型默认" onChange={event=>patch({temperature:event.target.value})}/></label>
      <label className="check wide"><input type="checkbox" checked={form.isDefault} onChange={event=>patch({isDefault:event.target.checked})}/>设为默认 Agent</label>
      </div></fieldset>
      {error&&<p className="error" role="alert">{error}</p>}<p className="status" role="status">{busy?'正在处理，请稍候…':status}</p>
      <div className="row"><button disabled={busy}>{busy?'保存中…':'保存配置'}</button><button className="outline" type="button" disabled={busy} onClick={reset}>取消编辑</button></div>
    </form></div>
    <section className="panel timezone"><h2>显示时区</h2><p className="muted">复习时间以 UTC 保存，按你的时区展示。</p><form className="row" onSubmit={event=>{event.preventDefault();void run(()=>api('auth/profile',{method:'PATCH',body:JSON.stringify({timezone})}).then(()=>onUser({...user,timezone})),'时区已更新')}}><label>时区<input value={timezone} onChange={event=>setTimezone(event.target.value)} placeholder="Asia/Shanghai"/></label><button disabled={busy}>保存时区</button></form></section>
  </>;
}
