'use client';
import { useEffect,useRef,useState } from 'react';
import { api,post,uid,errorText } from './api';
import type { Attempt,Review,Question } from './types';
import type { questions,Citation } from '../lib/schema';
export default function Study({card,open,initialAttempt,assistance,onClose,onRated,onCitation}:{card:Review;open:boolean;initialAttempt?:Attempt;assistance:boolean;onClose:()=>void;onRated:()=>Promise<void>;onCitation:(citation:Citation)=>void}){
  const dialog=useRef<HTMLDialogElement>(null);const [question,setQuestion]=useState<Question>(card.question),[answer,setAnswer]=useState(''),[assisted,setAssisted]=useState(assistance),[attempt,setAttempt]=useState<Attempt|null>(initialAttempt?.answer?initialAttempt:null),[reference,setReference]=useState<typeof questions.$inferSelect|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reason,setReason]=useState(''),[corrected,setCorrected]=useState('');const submission=useRef(initialAttempt?.idempotencyKey||uid());
  useEffect(()=>{if(open&&!dialog.current?.open)dialog.current?.showModal();if(!open&&dialog.current?.open)dialog.current.close()},[open]);
  useEffect(()=>{if(assistance)setAssisted(true)},[assistance]);
  useEffect(()=>{if(attempt?.assessment)void api<typeof questions.$inferSelect>('attempts/'+attempt.id+'/reference').then(setReference).catch(error=>setError(errorText(error)))},[attempt]);
  async function submit(value:string){setBusy(true);setError('');try{setAttempt(await post<Attempt>('cards/'+card.id+'/attempts',{answer:value,assisted,questionId:question.id,idempotencyKey:submission.current}));await onRated()}catch(error){setError(errorText(error));const saved=await api<Attempt[]>('attempts').catch(()=>[]);const pending=saved.find(item=>item.idempotencyKey===submission.current);if(pending)setAttempt(pending)}finally{setBusy(false)}}
  async function run(operation:()=>Promise<void>){setBusy(true);setError('');try{await operation()}catch(error){setError(errorText(error))}finally{setBusy(false)}}
  const feedback=attempt?.assessment;
  return <dialog className="study-dialog" ref={dialog} onCancel={event=>{event.preventDefault();if(!busy)onClose()}} onClose={onClose} aria-labelledby="study-title"><div className="row spread"><p className="eyebrow">{card.title} / {question.remedy?'讲解后的再次测试':'主动回忆'}</p><button className="text" disabled={busy} onClick={onClose}>关闭 ×</button></div><h2 id="study-title">{question.goal}</h2>
    {!attempt?<form onSubmit={event=>{event.preventDefault();void submit(answer)}}><p className="study-question">{question.prompt}</p><label>你的回答<textarea required rows={7} maxLength={12000} value={answer} onChange={event=>setAnswer(event.target.value)} placeholder="先尝试用自己的话回答，再查看评分与原文。"/></label><label className="check"><input type="checkbox" checked={assisted} disabled={assistance} onChange={event=>setAssisted(event.target.checked)}/>本轮已查看原文、提示或讲解</label><p className="muted small">{question.remedy?'即时补救练习不会单独更新 FSRS。':'查看参考答案前先提交；无法回忆会保留为失败记录。'}</p><div className="row"><button disabled={busy}>{busy?'评分中…':'提交并评分'}</button><button className="outline" type="button" disabled={busy} onClick={()=>void submit('暂时想不起来')}>暂时想不起来</button></div></form>:<>
      <p className="muted">本轮作答：{attempt.answer}</p>
      {!feedback?<div className="notice"><p>答案已保存，评分尚未完成，可安全重试。</p><button disabled={busy} onClick={()=>run(async()=>setAttempt(await post<Attempt>('attempts/'+attempt.id+'/grade')))}>重试评分</button></div>:<>
        <div className="score"><strong>{feedback.score}</strong><span>/ 100 · {attempt.correction?'用户修正后的得分':'本轮 AI 评分'}{attempt.assisted?' · 辅助作答':' · 独立作答'}</span></div><p>{feedback.feedback}</p>
        <ul className="feedback-points">{feedback.points.map(point=><li key={point.index}><strong>{reference?.rubric[point.index]?.point||'评分要点 '+(point.index+1)} · {point.earned}/{reference?.rubric[point.index]?.weight??'—'}</strong><p>{point.feedback}</p></li>)}</ul>
        {reference&&<details><summary>参考答案与原文依据</summary><p>{reference.answer}</p>{reference.citations.map((citation,index)=><button className="citation" key={index} onClick={()=>{onClose();onCitation(citation)}}>“{citation.quote}” · 查看原文 →</button>)}</details>}
        {!attempt.ratedAt&&attempt.kind!=='remedy'&&<details><summary>纠正 AI 的评分</summary><form className="correction" onSubmit={event=>{event.preventDefault();void run(async()=>{setAttempt(await post<Attempt>('attempts/'+attempt.id+'/correction',{score:Number(corrected),reason}));await onRated()})}}><label>修正得分<input type="number" required min={0} max={100} value={corrected} onChange={event=>setCorrected(event.target.value)}/></label><label>纠正依据<textarea required value={reason} onChange={event=>setReason(event.target.value)} maxLength={1500}/></label><button disabled={busy}>保存修正记录</button></form></details>}
        {attempt.kind==='remedy'?<p className="notice">这是讲解后的即时测试，结果已保存，不额外计为一次成功复习。</p>:attempt.ratedAt?<p className="notice">本轮评级已保存，复习时间已更新。</p>:<><h3>确认本轮记忆评级</h3><p className="muted small">AI 建议 {feedback.recommendation}。失败或辅助后作答需保留 Again；本轮得分不等于长期掌握。</p><div className="ratings">{(['Again','Hard','Good','Easy'] as const).map((rating,index)=><button key={rating} disabled={busy||rating!=='Again'&&(attempt.assisted||feedback.score<60||attempt.answer==='暂时想不起来')} onClick={()=>run(async()=>{await post('attempts/'+attempt.id+'/rating',{rating});setAttempt(await api<Attempt>('attempts/'+attempt.id));await onRated()})}>{['忘记了','想起但困难','顺利想起','轻松想起'][index]}<small>{rating}</small></button>)}</div></>}
        <button className="outline" disabled={busy} onClick={()=>run(async()=>{const next=await post<Question>('attempts/'+attempt.id+'/remedy');setQuestion(next);setAttempt(null);setReference(null);setAnswer('');setAssisted(true);submission.current=uid()})}>换一道题，再次测试 →</button>
      </>}
    </>}{error&&<p className="error" role="alert">{error}</p>}{busy&&<p role="status" className="muted">正在处理，请稍候…</p>}
  </dialog>;
}
